import os

GITHUB_TOKEN: str = os.environ["GITHUB_TOKEN"]
GITHUB_REPO_ID: str = os.environ["GITHUB_REPO_ID"]

GITHUB_MAIN_BRANCH: str = os.environ.get("GITHUB_MAIN_BRANCH", "main")

OBJECT_STORAGE_ENDPOINT_URL: str = os.environ.get("OBJECT_STORAGE_ENDPOINT_URL")
OBJECT_STORAGE_ACCESS_KEY_ID: str = os.environ.get("OBJECT_STORAGE_ACCESS_KEY_ID")
OBJECT_STORAGE_SECRET_ACCESS_KEY: str = os.environ.get("OBJECT_STORAGE_SECRET_ACCESS_KEY")
